### PR TITLE
Implement CI pipeline

### LINKED ISSUE #41: Add support for Travis CI
Would be nice to execute some commands on PR and new commit. I'm thinking about checking that compilation and tests pass.
Something like: 

`cargo check --examples --all-features`
To compile (without generating the binaries) libraries and examples with all features enabled;

`cargo test --all-features`
To compile and run all the tests (might be necessary here to restrict the number of threads in which the tests are parallely executed to avoid finishing resources with the flag --test-threads);

`cargo +nightly check --benches --all-features`
To also compile the benchmarks

### PR DESCRIPTION
**Pull request by cronicc**

### CODE REVIEW

**Comment by cronicc** [comment]
@DanieleDiBenedetto @phoinic currently failing tests with this PR based on https://github.com/HorizenOfficial/ginger-lib/commit/8973e8649560241bbd0a3d1c9c8f625d182a4d75

**On 1.51.0:**
https://travis-ci.com/github/HorizenOfficial/ginger-lib/jobs/507426650#L504-L537
```
+cd algebra
+cargo check --features bls12_381
   Compiling algebra v0.1.0 (/build/algebra)
error[E0433]: failed to resolve: could not find `jubjub` in `fields`
 --> algebra/src/fields/bls12_381/fr.rs:1:24
  |
1 | pub use crate::fields::jubjub::fq::{Fq as Fr, FqParameters as FrParameters};
  |                        ^^^^^^ could not find `jubjub` in `fields`
error[E0432]: unresolved import `crate::fields::bls12_381::Fr`
  --> algebra/src/curves/bls12_381/g1.rs:10:25
   |
10 |         bls12_381::{Fq, Fr},
   |                         ^^
   |                         |
   |                         no `Fr` in `fields::bls12_381`
   |                         help: a similar name exists in the module (notice the capitalization): `fr`
error[E0432]: unresolved import `crate::fields::bls12_381::Fr`
  --> algebra/src/curves/bls12_381/g2.rs:13:30
   |
[0m13 |         bls12_381::{Fq, Fq2, Fr},
   |                              ^^
   |                              |
   |                              no `Fr` in `fields::bls12_381`
   |                              help: a similar name exists in the module (notice the capitalization): `fr`
error: aborting due to 3 previous errors
Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `algebra`
To learn more, run the command again with --verbose.
```

https://travis-ci.com/github/HorizenOfficial/ginger-lib/jobs/507426650#L1542-L1643
```
+ cargo test --all-features
[...]
   Doc-tests algebra
running 4 tests
test src/serialize/mod.rs - serialize::CanonicalSerialize (line 44) ... FAILED
test src/lib.rs - log2_floor (line 88) ... FAILED
test src/serialize/mod.rs - serialize::CanonicalDeserialize (line 114) ... FAILED
test src/lib.rs - log2 (line 65) ... FAILED
failures:
---- src/serialize/mod.rs - serialize::CanonicalSerialize (line 44) stdout ----
error[E0465]: multiple rlib candidates for `algebra` found
 --> src/serialize/mod.rs:44:1
  |
3 | extern crate algebra;
  | ^^^^^^^^^^^^^^^^^^^^^
  |
note: candidate #1: /build/target/debug/deps/libalgebra-e2985d3aba5114d8.rlib
 --> src/serialize/mod.rs:44:1
  |
3 | extern crate algebra;
  | ^^^^^^^^^^^^^^^^^^^^^
note: candidate #2: /build/target/debug/deps/libalgebra-febf8205eabae830.rlib
 --> src/serialize/mod.rs:44:1
  |
3 | extern crate algebra;
  | ^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
Couldn't compile the test.
---- src/lib.rs - log2_floor (line 88) stdout ----
error[E0465]: multiple rlib candidates for `algebra` found
 --> src/lib.rs:87:1
  |
2 | extern crate algebra;
  | ^^^^^^^^^^^^^^^^^^^^^
  |
note: candidate #1: /build/target/debug/deps/libalgebra-e2985d3aba5114d8.rlib
 --> src/lib.rs:87:1
  |
2 | extern crate algebra;
  | ^^^^^^^^^^^^^^^^^^^^^
note: candidate #2: /build/target/debug/deps/libalgebra-febf8205eabae830.rlib
 --> src/lib.rs:87:1
  |
2 | extern crate algebra;
  | ^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
Couldn't compile the test.
---- src/serialize/mod.rs - serialize::CanonicalDeserialize (line 114) stdout ----
error[E0465]: multiple rlib candidates for `algebra` found
 --> src/serialize/mod.rs:114:1
  |
3 | extern crate algebra;
  | ^^^^^^^^^^^^^^^^^^^^^
  |
note: candidate #1: /build/target/debug/deps/libalgebra-e2985d3aba5114d8.rlib
 --> src/serialize/mod.rs:114:1
  |
3 | extern crate algebra;
  | ^^^^^^^^^^^^^^^^^^^^^
note: candidate #2: /build/target/debug/deps/libalgebra-febf8205eabae830.rlib
 --> src/serialize/mod.rs:114:1
  |
3 | extern crate algebra;
  | ^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
Couldn't compile the test.
---- src/lib.rs - log2 (line 65) stdout ----
error[E0465]: multiple rlib candidates for `algebra` found
 --> src/lib.rs:64:1
  |
2 | extern crate algebra;
  | ^^^^^^^^^^^^^^^^^^^^^
  |
note: candidate #1: /build/target/debug/deps/libalgebra-e2985d3aba5114d8.rlib
 ;12m--> src/lib.rs:64:1
  |
2 | extern crate algebra;
  | ^^^^^^^^^^^^^^^^^^^^^
note: candidate #2: /build/target/debug/deps/libalgebra-febf8205eabae830.rlib
 --> src/lib.rs:64:1
  |
2 | extern crate algebra;
  | ^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
Couldn't compile the test.
failures:
    src/lib.rs - log2 (line 65)
    src/lib.rs - log2_floor (line 88)
    src/serialize/mod.rs - serialize::CanonicalDeserialize (line 114)
    src/serialize/mod.rs - serialize::CanonicalSerialize (line 44)
test result: FAILED. 0 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.07s
```

**On nightly-2021-04-25:**

https://travis-ci.com/github/HorizenOfficial/ginger-lib/jobs/507426651#L504-L680
```
+ cargo +nightly-2021-04-25 check --all-features --tests --benches
[...]
error: could not compile `algebra`
```

again algebra
https://travis-ci.com/github/HorizenOfficial/ginger-lib/jobs/507426651#L727-L810
```
+ cd algebra
+ cargo +nightly-2021-04-25 check --all-features --tests --benches
[...]
error: could not compile `algebra`
```

cargo test --all-features never completes/stuck in endless loop, also tried on a powerful machine, still running after 24h. Also the case for `RUSTFLAGS="-C target-feature=+bmi2,+adx --emit=asm" cargo +nightly-2021-04-25 test --all-features`
https://travis-ci.com/github/HorizenOfficial/ginger-lib/jobs/507426651#L1798-L1849
```
+ cargo +nightly-2021-04-25 test --all-features
     Running unittests (target/debug/deps/primitives-c65eb7fd10014adc)
running 55 tests
[...]
test merkle_tree::field_based_mht::optimized::test::merkle_tree_path_test_mnt4 has been running for over 60 seconds
test merkle_tree::field_based_mht::optimized::test::merkle_tree_path_test_mnt6 has been running for over 60 seconds
```

**Comment by 95DDB** [comment]
@cronicc Some of the errors were alread fixed in https://github.com/HorizenOfficial/ginger-lib/commit/d1cf2cf5e7d9cf03a0bead0a36bb37facdeb2b7a

**Review by lander86 — APPROVED** [review]

**Comment by cronicc** [comment]
@DanieleDiBenedetto I've rebased ontop of https://github.com/HorizenOfficial/ginger-lib/commit/d1cf2cf5e7d9cf03a0bead0a36bb37facdeb2b7a and all the algebra issues seem to be solved now.

Only thing still failing seems to be:
```
+ cargo +nightly-2021-04-25 test --all-features
     Running unittests (target/debug/deps/primitives-c65eb7fd10014adc)
running 55 tests
[...]
test merkle_tree::field_based_mht::optimized::test::merkle_tree_path_test_mnt4 has been running for over 60 seconds
test merkle_tree::field_based_mht::optimized::test::merkle_tree_path_test_mnt6 has been running for over 60 seconds
```

**Comment by cronicc** [comment]
Rebased on top of https://github.com/HorizenOfficial/ginger-lib/tree/development_tmp_fixes

**Review by 95DDB — APPROVED** [review]

**Pull request merged**
